
cd moa-release-2016.04/
echo -e "Sección 2.2.1 -> Semilla 2\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.WaveformGenerator -i 2) -i 1000000 -f 10000"
echo -e "Sección 2.2.1 -> Semilla 1\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.WaveformGenerator -i 1) -i 1000000 -f 10000"
echo -e "Sección 2.2.1 -> Semilla 3\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.WaveformGenerator -i 3) -i 1000000 -f 10000"
echo -e "Sección 2.2.1 -> Semilla 4\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.WaveformGenerator -i 4) -i 1000000 -f 10000"
echo -e "Sección 2.2.1 -> Semilla 5\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.WaveformGenerator -i 5) -i 1000000 -f 10000"
echo -e "Fin Sección 2.2.1\n"

echo -e "Sección 2.2.2 -> Semilla 2\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 2) -i 1000000 -f 10000"
echo -e "Sección 2.2.2 -> Semilla 1\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 1) -i 1000000 -f 10000"
echo -e "Sección 2.2.2 -> Semilla 3\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 3) -i 1000000 -f 10000"
echo -e "Sección 2.2.2 -> Semilla 4\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 4) -i 1000000 -f 10000"
echo -e "Sección 2.2.2 -> Semilla 5\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 5) -i 1000000 -f 10000"
echo -e "Fin Sección 2.2.2\n"
