
cd moa-release-2016.04/
echo -e "Sección 2.3.1 -> Semilla 2\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 2 -i 2000000"
echo -e "Sección 2.3.1 -> Semilla 1\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 1 -i 2000000"
echo -e "Sección 2.3.1 -> Semilla 3\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 3 -i 2000000"
echo -e "Sección 2.3.1 -> Semilla 4\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 4 -i 2000000"
echo -e "Sección 2.3.1 -> Semilla 5\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 5 -i 2000000"
echo -e "Fin Sección 2.3.1\n"

echo -e "Sección 2.3.2 -> Semilla 2\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 2 -i 2000000"
echo -e "Sección 2.3.2 -> Semilla 1\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 1 -i 2000000"
echo -e "Sección 2.3.2 -> Semilla 3\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 3 -i 2000000"
echo -e "Sección 2.3.2 -> Semilla 4\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 4 -i 2000000"
echo -e "Sección 2.3.2 -> Semilla 5\n"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateInterleavedTestThenTrain -l moa.classifiers.trees.HoeffdingAdaptiveTree -s (generators.RandomRBFGeneratorDrift -s 0.001 -a 7 -n 3) -r 5 -i 2000000"
echo -e "Fin Sección 2.3.2\n"
