
cd moa-release-2016.04/
echo "Sección 2.1.1 -> Entrenamiento semilla 2"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingTree -s (generators.WaveformGenerator -i 2) -m 1000000"
echo "Sección 2.1.1 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.1 -> Entrenamiento semilla 1"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingTree -s (generators.WaveformGenerator -i 1) -m 1000000"
echo "Sección 2.1.1 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.1 -> Entrenamiento semilla 3"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingTree -s (generators.WaveformGenerator -i 3) -m 1000000"
echo "Sección 2.1.1 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.1 -> Entrenamiento semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingTree -s (generators.WaveformGenerator -i 4) -m 1000000"
echo "Sección 2.1.1 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.1 -> Entrenamiento semilla 5"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingTree -s (generators.WaveformGenerator -i 5) -m 1000000"
echo "Sección 2.1.1 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingTree -s (generators.WaveformGenerator -i 4)"
echo -e "Fin Sección 2.1.1\n"

echo -e "\nSección 2.1.2 -> Entrenamiento semilla 2"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 2) -m 1000000"
echo "Sección 2.1.2 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.2 -> Entrenamiento semilla 1"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 1) -m 1000000"
echo "Sección 2.1.2 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.2 -> Entrenamiento semilla 3"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 3) -m 1000000"
echo "Sección 2.1.2 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.2 -> Entrenamiento semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 4) -m 1000000"
echo "Sección 2.1.2 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 4)"
echo -e "\nSección 2.1.2 -> Entrenamiento semilla 5"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "LearnModel -l trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 5) -m 1000000"
echo "Sección 2.1.2 -> Evaluación semilla 4"
java -cp moa.jar -javaagent:sizeofag.jar moa.DoTask "EvaluateModel -m trees.HoeffdingAdaptiveTree -s (generators.WaveformGenerator -i 4)"
echo -e "Fin Sección 2.1.2\n"